package com.example.android.tflitecamerademo;

import android.content.Intent;
import android.graphics.Bitmap;
import android.location.Location;

import java.util.List;

public class ImageData {
    // The image itself
    public Bitmap bitmapImage;
    //Location data
    public double longitude;
    public double latitude;
    public double altitude;
    // The label array generated by the model (ordered by probability)
    public List<String> modelGeneratedLabels;
    // The probability of the labels  (as generated by the model)
    public List<String> labelProbabilities;
    // The label array following user-correction
    public List<String> userCorrectedLabels;
    // Did the user verify the labels (or just send?)
    public boolean UserVerified;

    public ImageData(Bitmap img, double lon, double lat, double alt, List<String> modelLabels, List<String> userLabels, boolean verified){
        bitmapImage = img;
        longitude = lon;
        latitude = lat;
        altitude = alt;
        modelGeneratedLabels = modelLabels;
        userCorrectedLabels = userLabels;
        UserVerified = verified;
    }

    public ImageData(Bitmap img, List<String> modelLabels, List<String> userLabels, boolean verified) {
        new ImageData(img, 0, 0, 0, modelLabels, userLabels, verified);
    }

}
