package com.example.android.tflitecamerademo;

import android.graphics.Bitmap;

import java.io.ByteArrayOutputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.PriorityQueue;

public class ImageData {
    // The image itself
    public Bitmap image;
    //Location data for the image
    private double longitude;
    private double latitude;
    private double altitude;

    //Campus location
    private int roomnNmber;
    private int floorNumber;
    private String building;
    // The label array generated by the model (ordered by probability)
    public List<String> modelGeneratedLabels;
    // The probability of the labels  (as generated by the model)
    public List<String> labelProbabilities;
    // The label array following user-correction
    public List<String> userCorrectedLabels;
    // Did the user verify the labels (or just send?)
    public boolean UserVerified;
    //Blank if the user has not uploaded the image
    public String URL = "";

    public long ClassificationTimeMs;

    public PriorityQueue<Map.Entry<String, Float>> SortedLabels = new PriorityQueue<>();
    public String errorString;


    public ImageData(Bitmap img, double lon, double lat, double alt, List<String> modelLabels, List<String> userLabels, boolean verified) {
        this.image = img;
        this.longitude = lon;
        this.latitude = lat;
        this.altitude = alt;
        this.modelGeneratedLabels = modelLabels;
        this.userCorrectedLabels = userLabels;
        this.UserVerified = verified;
    }

    public ImageData(Bitmap img, List<String> modelLabels, List<String> userLabels, boolean verified) {
        this(img, 0, 0, 0, modelLabels, userLabels, verified);
    }

    public ImageData(Bitmap img, double lon, double lat, double alt) {
        this(img, lon, lat, alt, new ArrayList<String>(), new ArrayList<String>(), false);

    }

    public ImageData(Bitmap img) {
        this(img, 0, 0, 0, new ArrayList<String>(), new ArrayList<String>(), false);

    }

    public ImageData() {
    }

    public void SetURL(String url) {
        this.URL = url;
    }

    public void SetLocation(double lat, double lon, double alt) {
        this.latitude = lat;
        this.longitude = lon;
        this.altitude = alt;
    }

    public void SetCampusLocation() {

    }

    //For setting headers of request
    public String PrintCoords() {
        return (Double.toString(latitude) + "," + Double.toString(longitude));
    }

    public String PrintLatitude() {
        return (Double.toString(latitude));
    }
    public String PrintLongitude() {
        return (Double.toString(longitude));
    }

    public String PrintAltitude() {
        return Double.toString(altitude);
    }

    public String GetImageURL() {
        return URL;
    }

    //Returns true if the Image has the required information to be sent in as a service request
    public boolean CheckComplete() {
        if (this.latitude == 0.0 || this.longitude == 0.0 || this.SortedLabels == null || this.SortedLabels.isEmpty() || this.URL == null) {
            return false;
        } else {
            return true;
        }
    }
}
